// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export { }

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConnectDialog: typeof import('./src/components/layout/sider/ConnectDialog.vue')['default']
    ControllerTab: typeof import('./src/components/layout/tabspace/ControllerTab.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    HashTab: typeof import('./src/components/layout/tabspace/keytab/HashTab.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeInfo: typeof import('./src/components/layout/tabspace/hometab/HomeInfo.vue')['default']
    HomeKeys: typeof import('./src/components/layout/tabspace/hometab/HomeKeys.vue')['default']
    HomeStatus: typeof import('./src/components/layout/tabspace/hometab/HomeStatus.vue')['default']
    HomeTab: typeof import('./src/components/layout/tabspace/hometab/HomeTab.vue')['default']
    KeyDetails: typeof import('./src/components/layout/tabspace/keytab/KeyDetails.vue')['default']
    ListTab: typeof import('./src/components/layout/tabspace/keytab/ListTab.vue')['default']
    SetTab: typeof import('./src/components/layout/tabspace/keytab/SetTab.vue')['default']
    Sider: typeof import('./src/components/layout/sider/Sider.vue')['default']
    SiderContent: typeof import('./src/components/layout/sider/SiderContent.vue')['default']
    SiderHeader: typeof import('./src/components/layout/sider/SiderHeader.vue')['default']
    SortedSetTab: typeof import('./src/components/layout/tabspace/keytab/SortedSetTab.vue')['default']
    StringTab: typeof import('./src/components/layout/tabspace/keytab/StringTab.vue')['default']
    TabSpace: typeof import('./src/components/layout/tabspace/TabSpace.vue')['default']
    TreeList: typeof import('./src/components/TreeList.vue')['default']
  }
}
